run: compile
        java Frontend
compile: Frontend.class Backend.class BackEndDeveloperTests.class City.class CityDataReader.class DataWranglerTests.class FrontEndDeveloperTests.class RedBlackTree.class CityDataReaderInterface.class FrontendInterface.class SortedCollectionInterface.class BackendInterface.class 

Frontend.class: Frontend.java
	javac Frontend.java

BackEndDeveloperTests.class: BackEndDeveloperTests.java
	javac BackEndDeveloperTests.java

Backend.class: Backend.java
	javac Backend.java

BackendInterface.class: BackendInterface.java
	javac BackendInterface.java

City.class: City.java
	javac City.java

CityDataReader.class: CityDataReader.java
	javac CityDataReader.java

CityDataReaderInterface.class: CityDataReaderInterface.java
	javac CityDataReaderInterface.java

CityInterface.class: CityInterface.java
	javac CityInterface.java

DataWranglerTests.class: DataWranglerTests.java
	javac DataWranglerTests.java

FrontEndDeveloperTests.class: FrontEndDeveloperTests.java
	javac FrontEndDeveloperTests.java

FrontendInterface.class: FrontendInterface.java
	javac FrontendInterface.java

RedBlackTree.class: RedBlackTree.java
	javac RedBlackTree.java

SortedCollectionInterface.class: SortedCollectionInterface.java
	javac SortedCollectionInterface.java

test: testData testBackend testFrontend

testFrontend: FrontEndDeveloperTests.class
	java FrontEndDeveloperTests

testBackend: BackEndDeveloperTests.class
	java BackEndDeveloperTests
        
testData: DataWranglerTests.class
	java DataWranglerTests
        
clean:
        $(RM) *.class